site_name: GastroWeb

nav:
  - Home: index.md
  - Gamificação: historia/historia-faccao.md
  - Visão do produto e projeto:
      - Visão geral do produto: visao-produto-projeto/visao-produto.md
      - Visão geral do projeto: visao-produto-projeto/visao-projeto.md
      - Processo de desenvolvimento de software: visao-produto-projeto/processo-de-desenvolvimento-de-software.md
  - Backlog do Produto: 
      - Backlog: backlog-produto/backlog.md
      - Priorização: backlog-produto/priorizacao-requisitos.md
      - MVP: backlog-produto/mvp.md
      - Alinhamento: backlog-produto/alinhamento_backlog.md
      - DoR e DoD: backlog-produto/dor_dod.md
      - DoD do MVP: backlog-produto/dod_mvp.md
  - Estudo de Casos:
      - PBB: estudo-caso/PBB.md
      - BDD: estudo-caso/BDD.md
      - USM: estudo-caso/USM.md
      - UC:  estudo-caso/UC.md
  - Design:
      - Padrões de Interface: design/padroes-interface.md
  - Sprints:
      - Sprint 1: sprints/sprint.md
  - Entregas:
      - Unidade 1: entregas/unidade-1.md
      - Unidade 2: entregas/unidade-2.md
      - Unidade 3: entregas/unidade-3.md
      - Unidade 4: entregas/unidade-4.md
  - Lições Aprendidas: visao-produto-projeto/licoes-aprendidas.md
repo_url: https://github.com/mdsreq-fga-unb/2023.2-GastroWeb
repo_name: GastroWeb
theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.tabs.sticky
    - toc.integrate
    - content.action.edit
    - content.action.view
    - navigation.top
    - content.tabs.link
    - content.code.annotation
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: purple
      toggle:
        icon: material/brightness-4
        name: Modo noturno
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Modo claro
