site_name: GastroWeb

nav:
  - Home: index.md
  - História da Facção: historia/historia-faccao.md
  - Visão do produto e projeto:
      - Visão geral do produto: visao-produto-projeto/visao-produto.md
      - Visão geral do projeto: visao-produto-projeto/visao-projeto.md
      - Processo de desenvolvimento de software: visao-produto-projeto/processo-de-desenvolvimento-de-software.md
  - Entregas:
      - Unidade 1: entregas/unidade-1.md
  - Lições Aprendidas: visao-produto-projeto/licoes-aprendidas.md
repo_url: https://github.com/mdsreq-fga-unb/2023.2-GastroWeb
repo_name: GastroWeb
theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - content.action.edit
    - content.action.view
    - navigation.top
    - content.tabs.link
    - content.code.annotation
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: purple
      toggle:
        icon: material/brightness-4
        name: Modo noturno
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Modo claro

